name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore Nika.sln

      - name: Format Check
        run: dotnet format Nika.sln --verify-no-changes

      - name: Build
        run: dotnet build Nika.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test Nika.sln --configuration Release --no-build
